"""initial schema

Revision ID: 97a27d579ea1
Revises: 
Create Date: 2026-07-25 12:02:13.192026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a27d579ea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_key'), 'webhook_events', ['event_key'], unique=True)
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reserved_account_reference', sa.String(length=64), nullable=True),
    sa.Column('reserved_account_number', sa.String(length=32), nullable=True),
    sa.Column('reserved_bank_name', sa.String(length=128), nullable=True),
    sa.Column('reserved_account_name', sa.String(length=255), nullable=True),
    sa.Column('reserved_account_status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_invite_code'), 'communities', ['invite_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_community_id'), 'audit_logs', ['community_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_per_member', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_allocation', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='collectionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_per_member >= 0', name='ck_collections_amount_positive'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_community_id'), 'collections', ['community_id'], unique=False)
    op.create_index(op.f('ix_collections_share_token'), 'collections', ['share_token'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', name='ledgerentrytype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_ledger_amount_positive'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_type', 'reference_id', 'type', name='uq_ledger_reference')
    )
    op.create_index('ix_ledger_community_created', 'ledger_entries', ['community_id', 'created_at'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('admin', 'treasurer', 'auditor', 'member', name='memberrole', native_enum=False, length=20), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_community_id'), 'members', ['community_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_index('uq_members_community_user', 'members', ['community_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))
    op.create_table('collection_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'waived', name='entrystatus', native_enum=False, length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_due >= 0', name='ck_entries_amount_positive'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'member_id', name='uq_entry_collection_member')
    )
    op.create_index(op.f('ix_collection_entries_collection_id'), 'collection_entries', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_entries_member_id'), 'collection_entries', ['member_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid_out', name='expensestatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_bank_name', sa.String(length=128), nullable=True),
    sa.Column('destination_account_number', sa.String(length=32), nullable=True),
    sa.Column('destination_account_name', sa.String(length=255), nullable=True),
    sa.Column('payout_reference', sa.String(length=128), nullable=True),
    sa.Column('paid_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_out_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['paid_out_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_community_status', 'expenses', ['community_id', 'status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('channel', sa.Enum('checkout', 'manual_cash', 'manual_transfer', name='paymentchannel', native_enum=False, length=20), nullable=False),
    sa.Column('payment_reference', sa.String(length=64), nullable=False),
    sa.Column('monnify_transaction_reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'reversed', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('raw_verification_payload', sa.JSON(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['collection_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_collection_id'), 'payments', ['collection_id'], unique=False)
    op.create_index(op.f('ix_payments_entry_id'), 'payments', ['entry_id'], unique=False)
    op.create_index(op.f('ix_payments_member_id'), 'payments', ['member_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_entry_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_collection_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_expenses_community_status', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_collection_entries_member_id'), table_name='collection_entries')
    op.drop_index(op.f('ix_collection_entries_collection_id'), table_name='collection_entries')
    op.drop_table('collection_entries')
    op.drop_index('uq_members_community_user', table_name='members', postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_community_id'), table_name='members')
    op.drop_table('members')
    op.drop_index('ix_ledger_community_created', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_collections_share_token'), table_name='collections')
    op.drop_index(op.f('ix_collections_community_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_audit_logs_community_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_communities_invite_code'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_webhook_events_event_key'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
